services:
  web:
    build: ./project
    command: poetry run uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8005:8000
    depends_on:
      - db
    networks:
      - shared-network

  # minio-dermalert:
  #   image: minio/minio:latest
  #   container_name: minio-dermalert
  #   environment:
  #     - MINIO_ROOT_USER=minio
  #     - MINIO_ROOT_PASSWORD=minio123
  #   volumes:
  #     - ./data/minio:/data
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   command: server /data --console-address ":9001" 
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl --silent --fail http://127.0.0.1:9000/minio/health/ready || exit 1"]
  #     interval: 5s
  #     timeout: 2s
  #     retries: 10
  #   networks:
  #     - shared-network

  db:
    image: postgres:15.3
    expose:
      - 5432
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dermalert
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network

volumes:
  pgdata:

networks:
  shared-network:
    external: true