apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-dermacam
  namespace: dermacam
spec:
  acme:
    email: arthuralves1538@gmail.com
    privateKeySecretRef:
      name: cert-dermacam
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          ingressClassName: external-nginx
